name: Publish GraphIP Postgres Image [13]
on:
  push:
  schedule:
    - cron: '10 1 * * wed'  # every wednesday @ 01:10
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        MAXMIND_LICENSE_KEY: ${{ secrets.MAXMIND_LICENSE_KEY }}
      with:
        name: graphip/postgres
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        buildargs: MAXMIND_LICENSE_KEY
        tags: "latest,13"